server:
  port: 8080

spring:
  datasource:
    username: prod_username
    password: prod_password
    url: jdbc:mysql://server_ip:server_port?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: redis_server_ip
    port: {redis_sever_port}
    timeout: 1000
    password: prod_password
